=begin
#Brevo API

#Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 

The version of the OpenAPI document: 3.0.0
Contact: contact@brevo.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Brevo::CompaniesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CompaniesApi' do
  before do
    # run before each test
    @api_instance = Brevo::CompaniesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompaniesApi' do
    it 'should create an instance of CompaniesApi' do
      expect(@api_instance).to be_instance_of(Brevo::CompaniesApi)
    end
  end

  # unit tests for companies_attributes_get
  # Get company attributes
  # @param [Hash] opts the optional parameters
  # @return [Array<CompanyAttributesInner>]
  describe 'companies_attributes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_get
  # Get all Companies
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filters Filter by attrbutes. If you have filter for owner on your side please send it as {\&quot;attributes.owner\&quot;:\&quot;6299dcf3874a14eacbc65c46\&quot;}
  # @option opts [Integer] :linked_contacts_ids Filter by linked contacts ids
  # @option opts [String] :linked_deals_ids Filter by linked Deals ids
  # @option opts [Integer] :page Index of the first document of the page
  # @option opts [Integer] :limit Number of documents per page
  # @option opts [String] :sort Sort the results in the ascending/descending order. Default order is **descending** by creation if &#x60;sort&#x60; is not passed
  # @option opts [String] :sort_by The field used to sort field names.
  # @return [CompaniesList]
  describe 'companies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_id_delete
  # Delete a company
  # @param id Company ID to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'companies_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_id_get
  # Get a company
  # @param id Get Company Details
  # @param [Hash] opts the optional parameters
  # @return [Company]
  describe 'companies_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_id_patch
  # Update a company
  # @param id 
  # @param companies_id_patch_request Updated company details.
  # @param [Hash] opts the optional parameters
  # @return [Company]
  describe 'companies_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_link_unlink_id_patch
  # Link and Unlink company with contact and deal
  # @param id 
  # @param companies_link_unlink_id_patch_request Linked / Unlinked contacts and deals ids.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'companies_link_unlink_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_post
  # Create a company
  # @param companies_post_request Company create data.
  # @param [Hash] opts the optional parameters
  # @return [CompaniesPost200Response]
  describe 'companies_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
