=begin
#Brevo API

#Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 

The version of the OpenAPI document: 3.0.0
Contact: contact@brevo.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module Brevo
  class GetWhatsAppConfig
    # Id of the WhatsApp business account
    attr_accessor :whatsapp_business_account_id

    # Sending limit Information of the WhatsApp API account
    attr_accessor :sending_limit

    # Quality status of phone number associated with WhatsApp account. There are three quality ratings. example - **High (GREEN) , Medium (YELLOW) and Low(RED)**
    attr_accessor :phone_number_quality

    # Status information related to WhatsApp API account
    attr_accessor :whatsapp_business_account_status

    # Verification status information of the Business account
    attr_accessor :business_status

    # Status of the name associated with WhatsApp Phone number
    attr_accessor :phone_number_name_status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'whatsapp_business_account_id' => :'whatsappBusinessAccountId',
        :'sending_limit' => :'sendingLimit',
        :'phone_number_quality' => :'phoneNumberQuality',
        :'whatsapp_business_account_status' => :'whatsappBusinessAccountStatus',
        :'business_status' => :'businessStatus',
        :'phone_number_name_status' => :'phoneNumberNameStatus'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'whatsapp_business_account_id' => :'String',
        :'sending_limit' => :'String',
        :'phone_number_quality' => :'String',
        :'whatsapp_business_account_status' => :'String',
        :'business_status' => :'String',
        :'phone_number_name_status' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Brevo::GetWhatsAppConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Brevo::GetWhatsAppConfig`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'whatsapp_business_account_id')
        self.whatsapp_business_account_id = attributes[:'whatsapp_business_account_id']
      end

      if attributes.key?(:'sending_limit')
        self.sending_limit = attributes[:'sending_limit']
      end

      if attributes.key?(:'phone_number_quality')
        self.phone_number_quality = attributes[:'phone_number_quality']
      end

      if attributes.key?(:'whatsapp_business_account_status')
        self.whatsapp_business_account_status = attributes[:'whatsapp_business_account_status']
      end

      if attributes.key?(:'business_status')
        self.business_status = attributes[:'business_status']
      end

      if attributes.key?(:'phone_number_name_status')
        self.phone_number_name_status = attributes[:'phone_number_name_status']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      phone_number_quality_validator = EnumAttributeValidator.new('String', ["GREEN", "YELLOW", "RED"])
      return false unless phone_number_quality_validator.valid?(@phone_number_quality)
      whatsapp_business_account_status_validator = EnumAttributeValidator.new('String', ["APPROVED", "PENDING", "REJECTED"])
      return false unless whatsapp_business_account_status_validator.valid?(@whatsapp_business_account_status)
      phone_number_name_status_validator = EnumAttributeValidator.new('String', ["APPROVED", "PENDING", "REJECTED"])
      return false unless phone_number_name_status_validator.valid?(@phone_number_name_status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_quality Object to be assigned
    def phone_number_quality=(phone_number_quality)
      validator = EnumAttributeValidator.new('String', ["GREEN", "YELLOW", "RED"])
      unless validator.valid?(phone_number_quality)
        fail ArgumentError, "invalid value for \"phone_number_quality\", must be one of #{validator.allowable_values}."
      end
      @phone_number_quality = phone_number_quality
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] whatsapp_business_account_status Object to be assigned
    def whatsapp_business_account_status=(whatsapp_business_account_status)
      validator = EnumAttributeValidator.new('String', ["APPROVED", "PENDING", "REJECTED"])
      unless validator.valid?(whatsapp_business_account_status)
        fail ArgumentError, "invalid value for \"whatsapp_business_account_status\", must be one of #{validator.allowable_values}."
      end
      @whatsapp_business_account_status = whatsapp_business_account_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_name_status Object to be assigned
    def phone_number_name_status=(phone_number_name_status)
      validator = EnumAttributeValidator.new('String', ["APPROVED", "PENDING", "REJECTED"])
      unless validator.valid?(phone_number_name_status)
        fail ArgumentError, "invalid value for \"phone_number_name_status\", must be one of #{validator.allowable_values}."
      end
      @phone_number_name_status = phone_number_name_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          whatsapp_business_account_id == o.whatsapp_business_account_id &&
          sending_limit == o.sending_limit &&
          phone_number_quality == o.phone_number_quality &&
          whatsapp_business_account_status == o.whatsapp_business_account_status &&
          business_status == o.business_status &&
          phone_number_name_status == o.phone_number_name_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [whatsapp_business_account_id, sending_limit, phone_number_quality, whatsapp_business_account_status, business_status, phone_number_name_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Brevo.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
